### ISSUE TITLE
CH - add https://okh.now.sh to OKH main page.

### ISSUE THREAD

**Issue by rafaellaantoniou** [iop-alliance/okh-marketing#2]
Really we need someone to point the domain `search.openknowhow.org` at Zeit.co servers to get a more official looking domain. -kaspar

**Comment by kasbah** [comment]
Technical details. We need the following record added to the DNS:

- Type: CNAME
- Name: search.openknowhow.org
- Value: alias.zeit.co

**Comment by Ceciwantstolearn** [comment]
@rafaellaantoniou Hi Rafaella, any suggestions on the wordings for this section on the website? Briefing website developer now

**Comment by rafaellaantoniou** [comment]
> @rafaellaantoniou Hi Rafaella, any suggestions on the wordings for this section on the website? Briefing website developer now

In my opinion, it should mention that on this website there are links to the projects which have manifests, and there is a usable search engine which allows you to find what you're looking for (i.e. makes projects discoverable). Not sure on how this should be worded but that's the purpose behind it :) Hope this helps. @kasbah and others feel free to add anything here
