### ISSUE TITLE
RM - Online form for manifests should be ready next week (w/c 02/03/2020)

### ISSUE THREAD

**Issue by rafaellaantoniou** [iop-alliance/okh-marketing#7]

**Comment by pciavald** [comment]
i'm on it :+1:

**Comment by julianstirling** [comment]
Well done!

I have cloned the project, composed and spun-up the docker container, and check the site works locally. Lets see if I can actually do something useful enough to submit a merge request.

**Comment by MIE5R0** [comment]
I got this today from our developer Dietrich Jäger: https://en.oho.wiki/wiki/Special:FormEdit/ProjectManifest
Please let me know, whether it is still relevant...

**Comment by rafaellaantoniou** [comment]
> I got this today from our developer Dietrich Jäger: https://en.oho.wiki/wiki/Special:FormEdit/ProjectManifest
> Please let me know, whether it is still relevant...

Seems like a duplication... is it worth having both forms? Perhaps yes... as long as they are the same. Thoughts?

**Comment by MIE5R0** [comment]
Yes, like I said in the last marketing group meeting, we had commissioned this work a couple of weeks ago anyway. So, I thought I might as well share what we have now... At least now noone can claim that they don't know how to create manifest files ;-)

**Comment by pciavald** [comment]
Thanks for sharing ! Here's the link to the other form: https://form.openknowhow.org

**Comment by julianstirling** [comment]
More than one form is not a bad thing as this is a standard. Standards should be cross platform. While duplicated effort is not a great thing so early, the more places where people find a manifest creation form the better.

@MIE5R0 I couldn't type anything into the form, am I doing something wrong?

**Comment by rafaellaantoniou** [comment]
> @MIE5R0 I couldn't type anything into the form, am I doing something wrong?

I can't either - must be a bug.

**Comment by MIE5R0** [comment]
Hi @julianstirling @rafaellaantoniou , First of all I should have declared that it is still a test version :-)
Also, I just wanted to know, whether it still makes sense for us to pursue this further. I know think it does. Have you registered an account and logged in? Since it's a Wiki, you cannot make any edits without logging in. While we refine the form, we will certainly also have to include some explanations on how to use it and credits on the page...

**Comment by rafaellaantoniou** [comment]
> Have you registered an account and logged in? Since it's a Wiki, you cannot make any edits without logging in. While we refine the form, we will certainly also have to include some explanations on how to use it and credits on the page...

If there's something you need from us, can you open it up as a separate issue? I have a very busy month so I can't commit to too much until the end of March.

**Comment by MIE5R0** [comment]
> 
> 
> > Have you registered an account and logged in? Since it's a Wiki, you cannot make any edits without logging in. While we refine the form, we will certainly also have to include some explanations on how to use it and credits on the page...
> 
> If there's something you need from us, can you open it up as a separate issue? I have a very busy month so I can't commit to too much until the end of March.

Sure, for now we don't need anything. I will give an update here when we have progressed further on the form and open other issues in case we need input.
