### ISSUE TITLE
Renaming the org to "internet-of-production"

### ISSUE THREAD

**Issue by kasbah** [iop-alliance/okh-marketing#9]
Bit of a meta issue for everyone. Are you ok with us renaming this Github org to "~iop-org~" "internet-of-production" to consolidate the names a bit? https://openknowhow.org redirects to the alliance webpage as well now. @OpenKnowHow/okh-devs @OpenKnowHow/marketinggroup @rwb27 @mwweinberg @dubsnipe @lurnid

**Comment by pciavald** [comment]
I'm for renaming the repo for a broader scope, but as per the discussions to make the vocabulary clear I would propose to call the organization "InternetOfProduction"

**Comment by jtc42** [comment]
I agree with @pciavald. Given that IOP has a well established meaning in physics (and I imagine other fields too!) being super clear is worth it IMO

**Comment by kasbah** [comment]
It's just so long for a git URL though (which I often do type out by hand) :D  What if we add, the full name "Internet of Production Alliance" to the main page? Would that be enough?

**Comment by pciavald** [comment]
As the org name appears on every page of the repo and shortening it is only a convenience for a few devs at most, i would be against that. Is there some shortening service, dns redirection or even bash alias you could use instead?

**Comment by julianstirling** [comment]
I am in agreement with @pciavald. When you said "iop-org" my first thought was "When did the Institute of Physics take over!?"

We need to build a brand and a name people recognise, shortening everything to a three letter acronym harms this. Whereas I think you are probably the only person who is writing out the git url by hand

**Comment by kasbah** [comment]
In that case my suggestion is "internet-of-production" because "InternetOfProduction" is hard to read.

**Comment by pciavald** [comment]
Agreed for internet-of-production

**Comment by julianstirling** [comment]
`internet-of-production`  I agree!!

**Comment by kasbah** [comment]
Great, I'll wait a few days for anyone to object. Just to satisfy my need for succinctness I added [iop.link/git](https://iop.link/git) to the [URL shortener](https://github.com/OpenKnowHow/iop.link) (we also have [iop.link/okh](https://iop.link/okh) already by the way).

**Comment by rwb27** [comment]
I frequently type git URLs by hand, but I'd take the extra characters in exchange for a more meaningful URL.  I'd definitely get confused by iop.  +1 for `internet-of-production`.

**Comment by kasbah** [comment]
Looks like that already exists unfortunately: https://github.com/internet-of-production. So my best suggestion is "iop-alliance" since "InternetOfProduction" could easily be confused with that existing org. I agree "iop" may make physics people double-take but at least "IOP Alliance" is what people actually call our org.

**Comment by pciavald** [comment]
I would agree with that reasoning, but I think that an existing organisation wearing the same name with a similar scope of action may be an issue. That would be worth discussing with Andrew and the rest of the alliance.

**Comment by kasbah** [comment]
It is done.
